version: '3.7'
services:
  postgres:
    container_name: prez-archi-hexa-postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prez
    ports:
      - "5432:5432"
    volumes:
      - prez-archi-hexa:/applis/docker-compose/prez/data
volumes:
  prez-archi-hexa:
    external: true